### ISSUE TITLE
Deal with timezones

### ISSUE THREAD

**Issue by menor** [resmio/widget#25]
Always fun

**Comment by nsb** [comment]
At the moment we use a field in the availabilities called
local_date_formatted. This is a string with the time in local time.

http://api.resmio.com/v1/facility/the-fish/availability?limit=1&format=json

ons. 5. aug. 2015 kl. 20.19 skrev José Menor <notifications@github.com>:

**Comment by menor** [comment]
Ok, I am using the Date Object internally for everything except for the timeslots list where I use the formatted one just to render.

Then, what we send to the POST right now is the date object without converting it to local_timezone, right?

**Comment by nsb** [comment]
Yes, that sounds correct.

**Comment by menor** [comment]
You were right, I return the selected availability object to the server, and use the local_time_formatted to display
