### ISSUE TITLE
Add a testing framework

### ISSUE THREAD

**Issue by menor** [resmio/widget#26]
Tape is cool  if we switch to pure functional, but for now we need something like Karma or Mocha (Jest?)

**Comment by JannKleen** [comment]
And CircleCI Integration :sparkles:

**Comment by menor** [comment]
![](http://media.giphy.com/media/QRPSnJNNC1Ee4/giphy.gif)

**Comment by menor** [comment]
We can go with tape thanks to the shallow renderer from React, moving the CircleCI integration to a new issue
