### ISSUE TITLE
Handle the case when you have no availabilities on the day

### ISSUE THREAD

**Issue by menor** [resmio/widget#54]
Right now availabilities is undefined so the app breaks when trying to filter them

**Comment by menor** [comment]
@fabiennepimenta will work on this

it can be:
Closed whole day
No availabilities all day
No availabilities for that number of persons
No availabilities for a specific time

**Comment by fabiennepimenta** [comment]
I talked with @menor and we decided: 

- If the day is closed we show a message in the calendar saying that is closed.

- If the day is fully booked we show a fully booked error in the time selector ( or between calendar and time — I think is the best place to show it )  — But we should show a generic message like "No space for those Nr. people" for the case: 
- If I select 5 people but the restaurant just have space for 4. Same error ""No space for those Nr. people"

- If the restaurant have capacity for 10 people, number 11 can't be selected; 

- If I select 5 people, for today but in some hours the restaurant is full, those times appears with opacity and can NOT be selected. 


Did I forgot something @menor ?

**Comment by menor** [comment]
Looks perfect, muito obrigado

**Comment by fabiennepimenta** [comment]
@menor can you take a look on that? 

When the restaurant just have capacity for 10 guests:

![just 10 people](https://cloud.githubusercontent.com/assets/3285116/10100941/95cd5a3a-6395-11e5-91b6-8ceb20b4da30.png)

Restaurant is closed: 
![closed](https://cloud.githubusercontent.com/assets/3285116/10101031/3a23bde0-6396-11e5-8ec3-45602cdee90d.png)

No space available 
![nospaceavailable](https://cloud.githubusercontent.com/assets/3285116/10101043/4f499910-6396-11e5-9426-fc6120ae52e5.png)


Time not available:
![hours not available](https://cloud.githubusercontent.com/assets/3285116/10101050/6253b7de-6396-11e5-8a9e-c7df689d2751.png)

**Comment by menor** [comment]
In the first one, can we just omit the numbers that are after the restaurant limit instead of the opacity change? I can do it but I'll have to go through some hoops.

**Comment by fabiennepimenta** [comment]
Sure. Like this?

![1 copy 2](https://cloud.githubusercontent.com/assets/3285116/10101264/fa851826-6397-11e5-9ef8-457273e53f55.png)

**Comment by menor** [comment]
yep, that is what we currently have

**Comment by menor** [comment]
will be solved by #69
