### ISSUE TITLE
Create the timeslot component

### ISSUE THREAD

**Issue by menor** [resmio/widget#63]
Try to implement it like @fabiennepimenta designed it, if it's too complicated we'll start with something more simple. @nsb can help with it.
![image](https://cloud.githubusercontent.com/assets/1360794/10096944/d68b78b0-6375-11e5-9ed5-66d1c54a4675.png)

**Comment by menor** [comment]
Talked with @fabiennepimenta about it we agreed in this behaviour:
- Initial state of the component is closed with no timeslot selected
- After the date changes it should expand with no timeslot selected by default.
- Initial timeslot should be the first one available
- The top buttons act as a shortcut when you click on it, the list advances to the first timeslot for that period (lunch starts at 12:00 dinner at 18:00)
- If the user advances or moves the list back we should highlight the period button where most of the shown items are, if there are the same quantity of timeslots in both periods, we highlight the latest.
- The component collapses when the user picks a timeslot.

**Comment by fabiennepimenta** [comment]
yup! :) :+1:

**Comment by mmarder** [comment]
I would like to test it with having a default time picked already. Maybe @neocortex can find out what the most likely booking time is.

**Comment by menor** [comment]
I'm moving the filter buttons to a new 'enhancement' issue, it can be done I just don't know how much time it is going to take and I think we can live without it for now.
