### ISSUE TITLE
Data analysis for default values.

### ISSUE THREAD

**Issue by neocortex** [resmio/widget#74]
In the widget we want to set default values for the most likely number of persons, most likely day of visit, and most likely time of visit.

Therefor the following statistics need to be computed:

- Percentage of online bookings for today, tomorrow, day after tomorrow, and any time later.
- Percentage of number of covers in online bookings.
- Percentage of online bookings for a given time.

**Comment by neocortex** [comment]
@menor, @mmarder, @fabiennepimenta below are the results of the statistics you requested for the widget. I assume that the optimal default values should be:

- Date: Today
- Covers: 2
- Time: 7pm

Percentage of online bookings for today, tomorrow, day after tomorrow, and any time later:

![image](https://cloud.githubusercontent.com/assets/198898/10279846/3019fa64-6b69-11e5-975a-968fc42ed7ea.png)
![image](https://cloud.githubusercontent.com/assets/198898/10279856/3e91cc8e-6b69-11e5-9247-ed8886279353.png)

Percentage of number of covers in online bookings:

![image](https://cloud.githubusercontent.com/assets/198898/10279878/62f871fe-6b69-11e5-9075-0637a0bbec70.png)

Percentage of online bookings for a given time during the day:

![image](https://cloud.githubusercontent.com/assets/198898/10279899/86358a1c-6b69-11e5-8cf8-c6f03c4a6582.png)

**Comment by menor** [comment]
Gracias!

**Comment by nsb** [comment]
Cool
